### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by reallinfo** [skinnn/caffe-manager#3]
Hello @skinnn I would like to contribute to the caffe-manager. I designed a few logos. If you like one of these, I can send you a pr. Or Any other ideas?

I will waiting for feedback.

![caffemanager](https://user-images.githubusercontent.com/36298335/42942778-a198adca-8b69-11e8-91ae-29f239820ca4.jpg)

**Comment by skinnn** [comment]
Hi @reallinfo and thank you very much for the contribution. Yea the first and the last one are pretty cool. Could you maybe do some variations of those 2 with the text "caffe manager" in few different fonts? Just let me know what kind of credit would you like to be added for your contribution.
Thanks again! :)

**Comment by reallinfo** [comment]
Sure, I tried 3 different fonts with different color variations. The part I pointed out is my favorite. But still if you have a font that you especially want, I can apply it.

![cm](https://user-images.githubusercontent.com/36298335/42949104-b2a55680-8b79-11e8-814c-19bfc1285e40.jpg)

**Comment by reallinfo** [comment]
Also, I made the first logo a little more clean.

![cm](https://user-images.githubusercontent.com/36298335/42951303-90375ba2-8b7e-11e8-8a07-db25e428cce7.jpg)

**Comment by skinnn** [comment]
Awesome! I like those 2 variations you pointed out and the font is nice. I have only one font you can maybe try https://fonts.google.com/specimen/Nunito  - bold or extra bold.

**Comment by skinnn** [comment]
Thanks, it's nice but I like you're font more, the one you pointed out. Would you recommend any other color / gradient rather than brown / ocher? Black / blue maybe?

**Comment by skinnn** [comment]
Yes, these colors are way better. I like this one on the right black / blue. Can you just make one variation where text is below the image with both black and blue texts, and also make this gear just a little bit thicker, somewhere between this last and the first example you sent me?

**Comment by skinnn** [comment]
It looks great. I would need just the logo without the text, versions where text is on the side and below the logo with both black and blue texts. Also I would like to add information about your contribution to the README. You can send me a link to your website/portfolio if you want me to include those besides your GitHub profile and some contact info so I can contact you in the future if anything comes up. Thanks! :)

**Comment by reallinfo** [comment]
I sent the all files.  You can add my Github profile. Also, my e-mail address; komiserback@gmail.com

If you have any need, feel free to write me. Have a nice day!

https://github.com/skinnn/caffe-manager/pull/4
